# Generated by Django 5.2.5 on 2026-01-01 05:17

import apps.cliente.validators
import apps.solar.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncons', models.CharField(default='-----', max_length=20, verbose_name='Unidade Consumidora')),
                ('concessionaria', models.CharField(default='-----', max_length=20, verbose_name='Concessionária')),
                ('lat', models.DecimalField(blank=True, decimal_places=17, max_digits=25, null=True, verbose_name='Latitude (S)')),
                ('lon', models.DecimalField(blank=True, decimal_places=17, max_digits=25, null=True, verbose_name='Longitude (O)')),
                ('cep', models.CharField(default='-', max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cons_jan', models.IntegerField(default=0, verbose_name='Janeiro')),
                ('cons_fev', models.IntegerField(default=0, verbose_name='Fevereiro')),
                ('cons_mar', models.IntegerField(default=0, verbose_name='Março')),
                ('cons_abr', models.IntegerField(default=0, verbose_name='Abril')),
                ('cons_mai', models.IntegerField(default=0, verbose_name='Maio')),
                ('cons_jun', models.IntegerField(default=0, verbose_name='Junho')),
                ('cons_jul', models.IntegerField(default=0, verbose_name='Julho')),
                ('cons_ago', models.IntegerField(default=0, verbose_name='Agosto')),
                ('cons_set', models.IntegerField(default=0, verbose_name='Setembro')),
                ('cons_out', models.IntegerField(default=0, verbose_name='Outubro')),
                ('cons_nov', models.IntegerField(default=0, verbose_name='Novembro')),
                ('cons_dez', models.IntegerField(default=0, verbose_name='Dezembro')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Consumo Médio',
                'verbose_name_plural': 'Consumos Médios',
            },
        ),
        migrations.CreateModel(
            name='ArquivosUnidadeConsumidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Conta de Luz', 'Conta de Luz'), ('Planta de Localização', 'Planta de Localização'), ('Disposição dos Paineis', 'Disposição dos Paineis'), ('Diagrama Unifilar', 'Diagrama Unifilar'), ('Diagrama Trifilar', 'Diagrama Trifilar'), ('Mapa de Strings', 'Mapa de Strings'), ('Planta do Imóvel', 'Planta do Imóvel'), ('ART do Projeto', 'ART do Projeto'), ('Memorial Descritivo', 'Memorial Descritivo'), ('Registro INMETRO', 'Registro INMETRO'), ('Procuração', 'Procuração'), ('Documento do Cliente', 'Documento do Cliente'), ('Formulário de Solicitação', 'Formulário de Solicitação'), ('Proposta', 'Proposta'), ('Contrato Assinado', 'Contrato Assinado'), ('Orçamento', 'Orçamento'), ('Fotos', 'Fotos'), ('Outros', 'Outros')], default='Conta de Luz', max_length=100, verbose_name='Tipo de Arquivo')),
                ('arquivo', models.FileField(upload_to=apps.solar.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'dwg']), apps.cliente.validators.validate_file_mimetype, apps.cliente.validators.validate_file_size], verbose_name='Arquivos')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='solar.consumo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Por kWh'), ('2', 'Por Watt')], max_length=1, verbose_name='Tipo de Envio (Watt ou kWp/mês)')),
                ('equipamento', models.CharField(max_length=30)),
                ('potencia', models.FloatField(verbose_name='Potência ou Consumo')),
                ('horas', models.FloatField(verbose_name='Tempo de Uso (H)')),
                ('dias', models.IntegerField(verbose_name='Dias de Uso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.consumo')),
            ],
            options={
                'verbose_name': 'Consumo Adicional',
                'verbose_name_plural': 'Consumos Adicionais',
            },
        ),
        migrations.CreateModel(
            name='Irradiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrad_anual', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Anual')),
                ('irrad_jan', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Janeiro')),
                ('irrad_fev', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Fevereiro')),
                ('irrad_mar', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Março')),
                ('irrad_abr', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Abril')),
                ('irrad_mai', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Maio')),
                ('irrad_jun', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Junho')),
                ('irrad_jul', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Julho')),
                ('irrad_ago', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Agosto')),
                ('irrad_set', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Setembro')),
                ('irrad_out', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Outubro')),
                ('irrad_nov', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Novembro')),
                ('irrad_dez', models.FloatField(blank=True, default=0, null=True, verbose_name='Irradiação Dezembro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irradiacao', to='solar.consumo')),
            ],
            options={
                'verbose_name': 'Irradiação Média',
                'verbose_name_plural': 'Irradiações Médias',
            },
        ),
        migrations.CreateModel(
            name='PotGeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimento', models.IntegerField(default=100, verbose_name='Eficiência do Sistema %')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potger', to='cliente.cliente')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potger_consumo', to='solar.consumo')),
                ('irrad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potger_irrad', to='solar.irradiacao', verbose_name='Irradiação')),
            ],
            options={
                'verbose_name': 'Potência de Geração Necessária',
                'verbose_name_plural': 'Potências de Geração Necessárias',
            },
        ),
        migrations.CreateModel(
            name='Paineis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potpainel', models.IntegerField(default=0, verbose_name='Potencia do Painel (W)')),
                ('areadisp', models.FloatField(default=0, verbose_name='Area Disponivel')),
                ('paineisdesejados', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Painéis Desejada')),
                ('h', models.FloatField(default=0, verbose_name='Comprimento do Painel')),
                ('l', models.FloatField(default=0, verbose_name='Largura do Painel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis', to='solar.consumo')),
                ('potgeracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis_potger', to='solar.potgeracao', verbose_name='Potência de Geração')),
            ],
            options={
                'verbose_name': 'Paineis Necessários',
                'verbose_name_plural': 'Painéis Necessários',
            },
        ),
        migrations.CreateModel(
            name='GerEsperada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geresp', to='solar.consumo')),
                ('potsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geresp_potsis', to='solar.paineis', verbose_name='Potencia do Sistema')),
                ('pger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geresp_rend', to='solar.potgeracao', verbose_name='Potencia Necessária de Geração')),
            ],
            options={
                'verbose_name': 'Geração Esperada do Sistema',
                'verbose_name_plural': 'Gerações Esperadas dos Sistemas',
            },
        ),
    ]
