# Generated by Django 5.2.5 on 2026-01-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='status',
            field=models.BooleanField(choices=[('1', 'Prospecção'), ('2', 'Captação de Documentos'), ('3', 'Captação de Dados'), ('4', 'Análise Técnica'), ('5', 'Orçamento'), ('6', 'Aprovação do Cliente'), ('7', 'Execução do Projeto'), ('8', 'Projeto Concluído')], default='1', max_length=1, verbose_name='Etapa do Projeto'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude (S)'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude (O)'),
        ),
    ]
