# Generated by Django 5.2.5 on 2026-01-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('solar', '0002_consumo_status_alter_consumo_lat_alter_consumo_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumo',
            old_name='status',
            new_name='etapa',
        ),
        migrations.AlterField(
            model_name='consumo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_solar', to='cliente.cliente'),
        ),
    ]
