# Generated by Django 5.2.5 on 2026-01-03 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('solar', '0004_alter_consumo_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosunidadeconsumidora',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_files', to='solar.consumo'),
        ),
        migrations.AlterField(
            model_name='consumoadicional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_adicional', to='solar.consumo'),
        ),
        migrations.AlterField(
            model_name='geresperada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_geresp', to='solar.consumo'),
        ),
        migrations.AlterField(
            model_name='irradiacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_irradiacao', to='solar.consumo'),
        ),
        migrations.AlterField(
            model_name='paineis',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_paineis', to='solar.consumo'),
        ),
        migrations.AlterField(
            model_name='potgeracao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pger', to='cliente.cliente'),
        ),
        migrations.CreateModel(
            name='EnergiaProduzida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eprod_jan', models.FloatField(default=0, verbose_name='Janeiro')),
                ('eprod_fev', models.FloatField(default=0, verbose_name='Fevereiro')),
                ('eprod_mar', models.FloatField(default=0, verbose_name='Março')),
                ('eprod_abr', models.FloatField(default=0, verbose_name='Abril')),
                ('eprod_mai', models.FloatField(default=0, verbose_name='Maio')),
                ('eprod_jun', models.FloatField(default=0, verbose_name='Junho')),
                ('eprod_jul', models.FloatField(default=0, verbose_name='Julho')),
                ('eprod_ago', models.FloatField(default=0, verbose_name='Agosto')),
                ('eprod_set', models.FloatField(default=0, verbose_name='Setembro')),
                ('eprod_out', models.FloatField(default=0, verbose_name='Outubro')),
                ('eprod_nov', models.FloatField(default=0, verbose_name='Novembro')),
                ('eprod_dez', models.FloatField(default=0, verbose_name='Dezembro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geresp_Eprod', to='solar.geresperada')),
            ],
        ),
    ]
