# Generated by Django 5.2.5 on 2026-01-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_alter_arquivosunidadeconsumidora_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energiaproduzida',
            options={'verbose_name': 'Energia Produzida', 'verbose_name_plural': 'Energias Produzidas'},
        ),
        migrations.AddField(
            model_name='consumo',
            name='categoria',
            field=models.CharField(choices=[('3', 'B3 - COMERCIAL'), ('1', 'B1 - RESIDENCIAL')], default='1', max_length=1, verbose_name='Categoria do Empreendimento'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='concessionaria',
            field=models.CharField(choices=[('L', 'LIGHT'), ('E', 'ENEL')], default='L', max_length=20, verbose_name='Concessionária'),
        ),
    ]
