# Generated by Django 5.2.5 on 2026-01-08 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_alter_energiaproduzida_options_consumo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip', models.CharField(max_length=50, verbose_name='Material')),
                ('qnt', models.FloatField(verbose_name='Quantidade do Material')),
                ('unid', models.CharField(choices=[('M', 'Metros'), ('U', 'Unidade'), ('P', 'Peso')], default='U', max_length=1, verbose_name='Grandeza da Unidade')),
                ('preco_unit', models.FloatField(verbose_name='Preço Unitário')),
                ('preco_tot', models.FloatField(blank=True, null=True, verbose_name='Preço Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_solar', to='solar.consumo', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EcoProjetada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_kit', models.FloatField(verbose_name='Custo Kit Usina Solar')),
                ('mao_obra', models.FloatField(verbose_name='Custo Mão de Obra')),
                ('tarifa_el', models.FloatField(verbose_name='Valor Tarifa Elétrica (R$/kWh)')),
                ('ilum_public', models.FloatField(verbose_name='Valor Iluminação Publica')),
                ('fiob', models.IntegerField(default=60, verbose_name='Porcentagem Fio B (Lei 14.300/2022)')),
                ('ano_op', models.CharField(default='2026', max_length=4, verbose_name='Ano de operação da Usina')),
                ('margem', models.IntegerField(default=30, verbose_name='Margem de Lucro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economia_geracao', to='solar.consumo', verbose_name='Local')),
                ('geracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economia_geracao', to='solar.geresperada', verbose_name='Local')),
                ('material', models.ManyToManyField(related_name='economia_materia', to='solar.customaterial', verbose_name='Materiais')),
            ],
        ),
    ]
