# Generated by Django 5.2.5 on 2026-01-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_customaterial_ecoprojetada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customaterial',
            options={'verbose_name': 'Custo do Material', 'verbose_name_plural': 'Custo dos Materiais'},
        ),
        migrations.AlterModelOptions(
            name='ecoprojetada',
            options={'verbose_name': 'Retorno Projetado', 'verbose_name_plural': 'Retornos Projetados'},
        ),
        migrations.AlterField(
            model_name='customaterial',
            name='preco_tot',
            field=models.FloatField(default=0, verbose_name='Preço Total'),
        ),
    ]
