# Generated by Django 5.2.5 on 2026-01-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_alter_customaterial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoprojetada',
            name='custo_kit',
        ),
        migrations.RemoveField(
            model_name='ecoprojetada',
            name='mao_obra',
        ),
        migrations.RemoveField(
            model_name='ecoprojetada',
            name='margem',
        ),
        migrations.AlterField(
            model_name='consumoadicional',
            name='tipo',
            field=models.CharField(choices=[('1', 'Por kWh'), ('2', 'Por Watt')], max_length=1, verbose_name='Tipo de Envio (Watt ou kWh/mês)'),
        ),
        migrations.AlterField(
            model_name='ecoprojetada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economia_geracao', to='solar.consumo', verbose_name='Consumo'),
        ),
        migrations.AlterField(
            model_name='ecoprojetada',
            name='geracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economia_geracao', to='solar.geresperada', verbose_name='Geração Esperada'),
        ),
        migrations.CreateModel(
            name='CustosNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_kit', models.FloatField(verbose_name='Custo Kit Usina Solar')),
                ('mao_obra', models.FloatField(default=250, verbose_name='Custo Mão de Obra')),
                ('margem', models.IntegerField(default=30, verbose_name='Margem de Lucro')),
                ('engenharia', models.IntegerField(default=100, verbose_name='Custo Engenharia')),
                ('comissao_rep', models.IntegerField(default=3, verbose_name='Comissão Representante')),
                ('comissao_com', models.IntegerField(default=2, verbose_name='Comissão Comercial')),
                ('imposto', models.IntegerField(default=10, verbose_name='Impostos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_negocio', to='solar.paineis', verbose_name='Cliente')),
                ('custo_material', models.ManyToManyField(related_name='negocio_material', to='solar.customaterial', verbose_name='Materiais')),
            ],
        ),
        migrations.AddField(
            model_name='ecoprojetada',
            name='custo_negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='economia_negocio', to='solar.custosnegocio', verbose_name='Custos do Negocio'),
        ),
    ]
