# Generated by Django 5.2.5 on 2026-01-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_remove_ecoprojetada_custo_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoprojetada',
            name='custo_negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economia_negocio', to='solar.custosnegocio', verbose_name='Custos do Negocio'),
        ),
    ]
