# Generated by Django 5.2.5 on 2026-01-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_alter_ecoprojetada_custo_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='custosnegocio',
            name='paineis_herd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paineis_negocio', to='solar.paineis', verbose_name='Potencia de Instalação'),
        ),
        migrations.AlterField(
            model_name='custosnegocio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_negocio', to='solar.consumo', verbose_name='Consumo'),
        ),
    ]
