# Generated by Django 5.2.5 on 2026-01-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_custosnegocio_paineis_herd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custosnegocio',
            name='paineis_herd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis_negocio', to='solar.paineis', verbose_name='Potencia de Instalação'),
        ),
    ]
