# Generated by Django 5.2.5 on 2026-01-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_alter_custosnegocio_paineis_herd'),
    ]

    operations = [
        migrations.AddField(
            model_name='custosnegocio',
            name='art',
            field=models.FloatField(default=250, verbose_name='Custo da ART'),
        ),
        migrations.AlterField(
            model_name='custosnegocio',
            name='engenharia',
            field=models.IntegerField(default=100, verbose_name='Custo Engenharia por Painel'),
        ),
        migrations.AlterField(
            model_name='custosnegocio',
            name='mao_obra',
            field=models.FloatField(default=250, verbose_name='Custo Mão de Obra por Painel'),
        ),
    ]
