# Generated by Django 5.2.5 on 2026-01-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0013_custosnegocio_art_alter_custosnegocio_engenharia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custosnegocio',
            name='art',
            field=models.FloatField(default=271.47, verbose_name='Custo da ART'),
        ),
    ]
