# Generated by Django 5.2.5 on 2025-11-15 03:44

import apps.cliente.models
import apps.cliente.validators
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Cliente')),
                ('nome', models.CharField(max_length=100, verbose_name='Cliente')),
                ('doc', models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('tel1', models.CharField(max_length=11, verbose_name='Contato 1')),
                ('tel2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Contato 2')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cadastro', models.DateField(default=datetime.datetime.now, verbose_name='Data de Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivosClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Documento do Cliente', 'Documento do Cliente'), ('Proposta', 'Proposta'), ('Contrato Assinado', 'Contrato Assinado'), ('Orçamento', 'Orçamento'), ('Outros', 'Outros')], default='Documento do Cliente', max_length=100, verbose_name='Tipo de Arquivo')),
                ('arquivo', models.FileField(upload_to=apps.cliente.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.cliente.validators.validate_file_mimetype, apps.cliente.validators.validate_file_size], verbose_name='Arquivos')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cliente.cliente')),
            ],
        ),
    ]
