# Generated by Django 5.2.5 on 2025-11-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosclientes',
            name='tipo',
            field=models.CharField(choices=[('DC', 'Documento do Cliente'), ('PR', 'Proposta'), ('CA', 'Contrato Assinado'), ('OR', 'Orçamento'), ('OU', 'Outros')], default='Documento do Cliente', max_length=2, verbose_name='Tipo de Arquivo'),
        ),
    ]
