# Generated by Django 5.2.5 on 2025-11-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.CharField(max_length=100, verbose_name='Ambiente')),
                ('t_comodo', models.CharField(choices=[('Q', 'Quarto'), ('S', 'Salas'), ('B', 'Banheiro'), ('C', 'Cozinha, Copas, Lavanderias'), ('O', 'Escritório'), ('E', 'Área Externa'), ('V', 'Varanda'), ('H', 'Corredores')], default='S', max_length=1, verbose_name='Tipo de Ambiente')),
                ('perimetro', models.FloatField(verbose_name='Perimetro do Ambiente')),
                ('area', models.FloatField(verbose_name='Área do Ambiente')),
                ('tug', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qnt. TUGs')),
                ('tue', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qnt. TUEs')),
                ('iluminacao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pontos de Iluminação')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('local', models.CharField(max_length=100, verbose_name='Identificação do local')),
                ('cep', models.CharField(default='-', max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='CargasILUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_ilum', to='instEletricas.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='CargasTUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_pot', models.CharField(blank=True, choices=[('R', 'Aquecimento'), ('A', 'Ar Condicionados Janela/Split'), ('B', 'Ar Condicionado Central'), ('M', 'Motores'), ('S', 'Maq. Solda a Trafo, equip. Odonto-Medico Hopitalares')], default='W', max_length=1, null=True, verbose_name='Watts ou VA')),
                ('pot_tue', models.IntegerField(default=0, verbose_name='Potencia TUE')),
                ('t_carga', models.CharField(blank=True, choices=[('R', 'Aquecimento'), ('A', 'Ar Condicionados Janela/Split'), ('B', 'Ar Condicionado Central'), ('M', 'Motores'), ('S', 'Maq. Solda a Trafo, equip. Odonto-Medico Hopitalares')], default='R', max_length=1, null=True, verbose_name='Tipos de Cargas')),
                ('carga', models.CharField(max_length=100, verbose_name='Descritivo da Carga')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_tue', to='instEletricas.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='CargasTUG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_tug', to='instEletricas.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='Circuitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ckt_ambiente', to='instEletricas.ambientes')),
                ('ilum', models.ManyToManyField(blank=True, related_name='ckt_ilum', to='instEletricas.cargasilum')),
                ('tue', models.ManyToManyField(blank=True, related_name='ckt_tue', to='instEletricas.cargastue')),
                ('tug', models.ManyToManyField(blank=True, related_name='ckt_tug', to='instEletricas.cargastug')),
            ],
        ),
        migrations.AddField(
            model_name='ambientes',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_ambiente', to='instEletricas.local'),
        ),
    ]
