# Generated by Django 5.2.5 on 2026-01-01 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.CharField(max_length=100, verbose_name='Ambiente')),
                ('t_comodo', models.CharField(choices=[('Q', 'Quarto'), ('S', 'Salas'), ('B', 'Banheiro'), ('C', 'Cozinha, Copas, Lavanderias'), ('O', 'Escritório'), ('E', 'Área Externa'), ('V', 'Varanda'), ('H', 'Corredores')], default='S', max_length=1, verbose_name='Tipo de Ambiente')),
                ('perimetro', models.FloatField(verbose_name='Perimetro do Ambiente')),
                ('area', models.FloatField(verbose_name='Área do Ambiente')),
                ('tug', models.IntegerField(default=0, verbose_name='Qnt. TUGs Propostas')),
                ('tue', models.IntegerField(default=0, verbose_name='Qnt. TUEs Propostas')),
                ('iluminacao', models.IntegerField(default=0, verbose_name='Pontos de Iluminação Propostas')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
        migrations.CreateModel(
            name='CargasILUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_ilum', to='instEletricas.ambientes')),
            ],
            options={
                'verbose_name': 'Carga de Iluminação',
                'verbose_name_plural': 'Cargas de Iluminação',
            },
        ),
        migrations.CreateModel(
            name='CargasTUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_pot', models.CharField(blank=True, choices=[('W', 'Watts'), ('V', 'VA')], default='V', max_length=1, null=True, verbose_name='Watts ou VA')),
                ('pot_tue', models.IntegerField(default=0, verbose_name='Potencia TUE')),
                ('t_carga', models.CharField(blank=True, choices=[('R', 'Aquecimento'), ('A', 'Ar Condicionados Janela/Split'), ('B', 'Ar Condicionado Central'), ('M', 'Motores'), ('S', 'Maq. Solda a Trafo, equip. Odonto-Medico Hopitalares')], default='R', max_length=1, null=True, verbose_name='Tipos de Cargas')),
                ('carga', models.CharField(max_length=100, verbose_name='Descritivo da Carga')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_tue', to='instEletricas.ambientes')),
            ],
            options={
                'verbose_name': 'Carga de TUE',
                'verbose_name_plural': "Cargas de TUE's",
            },
        ),
        migrations.CreateModel(
            name='CargasTUG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_tug', to='instEletricas.ambientes')),
            ],
            options={
                'verbose_name': 'Carga TUG',
                'verbose_name_plural': "Cargas TUG's",
            },
        ),
        migrations.CreateModel(
            name='Circuitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50, verbose_name='Identificação do Circuito')),
                ('ckt', models.CharField(choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], default='M', max_length=1, verbose_name='Tipo do Circuito')),
                ('ilum', models.ManyToManyField(blank=True, related_name='ckt_ilum', to='instEletricas.cargasilum', verbose_name='Cargas de Iluminação')),
                ('tue', models.ManyToManyField(blank=True, related_name='ckt_tue', to='instEletricas.cargastue', verbose_name='Cargas TUEs')),
                ('tug', models.ManyToManyField(blank=True, related_name='ckt_tug', to='instEletricas.cargastug', verbose_name='Cargas TUGs')),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
            },
        ),
        migrations.CreateModel(
            name='Condutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ckts', models.IntegerField(default=1, verbose_name='Nº Máximo de CKTs em um trecho')),
                ('temp', models.IntegerField(default=30, verbose_name='Temperatura Ambiente Máxima')),
                ('mat_isol', models.CharField(choices=[('P', 'PVC'), ('E', 'EPR OU XLPE')], default='P', max_length=1, verbose_name='Material Isolante do Condutor')),
                ('ckt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cond_ckt', to='instEletricas.circuitos', verbose_name='Circuito')),
            ],
            options={
                'verbose_name': 'Condutor',
                'verbose_name_plural': 'Condutores',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(db_index=True, max_length=100, verbose_name='Identificação do local')),
                ('cep', models.CharField(db_index=True, default='-', max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=100, verbose_name='Numero')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
                ('rede', models.CharField(choices=[('1', '127/220 V'), ('2', '220/380 V')], default='1', max_length=1, verbose_name='Alimentação Concessionária')),
                ('tipo_rede', models.CharField(choices=[('M', 'Monofásica'), ('B', 'Bifásica'), ('T', 'Trifásica'), ('N', 'Instalação Nova')], default='N', max_length=1, verbose_name='Tipo de Rede')),
                ('status', models.BooleanField(choices=[('1', 'Prospecção'), ('2', 'Captação de Documentos'), ('3', 'Captação de Dados'), ('4', 'Análise Técnica'), ('5', 'Orçamento'), ('6', 'Aprovação do Cliente'), ('7', 'Execução do Projeto'), ('8', 'Projeto Concluído')], default='1', max_length=1, verbose_name='Etapa do Projeto')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_local', to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='EquilibrioFases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckt', models.ManyToManyField(blank=True, related_name='EqFase_ckt', to='instEletricas.circuitos', verbose_name='Circuito')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EqFase_local', to='instEletricas.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Equilíbrio de Fases',
                'verbose_name_plural': 'Equilíbrio de Fases',
            },
        ),
        migrations.CreateModel(
            name='Eletrodutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100, verbose_name='Trecho do Eletroduto')),
                ('conexoes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de Conexões para o eletroduto')),
                ('c_conex', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caracteristicas das conexões')),
                ('dist', models.IntegerField(blank=True, default=0, null=True, verbose_name='Comprimento do Trecho')),
                ('cond', models.ManyToManyField(blank=True, related_name='eletro_ckt', to='instEletricas.condutores', verbose_name='Condutores')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eletro_local', to='instEletricas.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Eletroduto',
                'verbose_name_plural': 'Eletrodutos',
            },
        ),
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilum', models.ManyToManyField(blank=True, related_name='demanda_ilum', to='instEletricas.cargasilum', verbose_name='Cargas de Iluminação')),
                ('tue', models.ManyToManyField(blank=True, related_name='demanda_tue', to='instEletricas.cargastue', verbose_name='Cargas TUEs')),
                ('tug', models.ManyToManyField(blank=True, related_name='demanda_tug', to='instEletricas.cargastug', verbose_name='Cargas TUGs')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demanda_local', to='instEletricas.local')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
        migrations.AddField(
            model_name='condutores',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cond_local', to='instEletricas.local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='circuitos',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ckt_local', to='instEletricas.local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='ambientes',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_ambiente', to='instEletricas.local'),
        ),
        migrations.CreateModel(
            name='Protecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prot_ckt', to='instEletricas.condutores', verbose_name='Condutores')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prot_local', to='instEletricas.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Proteção',
                'verbose_name_plural': 'Proteções',
            },
        ),
    ]
