# Generated by Django 5.2.5 on 2026-01-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='local',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='local',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
    ]
