# Generated by Django 5.2.5 on 2025-11-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambientes',
            options={'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='cargasilum',
            options={'verbose_name': 'Carga de Iluminação', 'verbose_name_plural': 'Cargas de Iluminação'},
        ),
        migrations.AlterModelOptions(
            name='cargastue',
            options={'verbose_name': 'Carga de TUE', 'verbose_name_plural': "Cargas de TUE's"},
        ),
        migrations.AlterModelOptions(
            name='cargastug',
            options={'verbose_name': 'Carga TUG', 'verbose_name_plural': "Cargas TUG's"},
        ),
        migrations.AlterModelOptions(
            name='circuitos',
            options={'verbose_name': 'Circuito', 'verbose_name_plural': 'Circuitos'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AddField(
            model_name='circuitos',
            name='nome',
            field=models.CharField(default='', max_length=20, verbose_name='Identificação do Circuito'),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='iluminacao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pontos de Iluminação Propostas'),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='tue',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qnt. TUEs Propostas'),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='tug',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qnt. TUGs Propostas'),
        ),
        migrations.AlterField(
            model_name='cargastue',
            name='t_pot',
            field=models.CharField(blank=True, choices=[('W', 'Watts'), ('V', 'VA')], default='V', max_length=1, null=True, verbose_name='Watts ou VA'),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ckt_local', to='instEletricas.local'),
        ),
    ]
