# Generated by Django 5.2.5 on 2025-11-11 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0002_alter_ambientes_options_alter_cargasilum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitos',
            name='ckt',
            field=models.CharField(choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], default='M', max_length=1, verbose_name='Tipo do Circuito'),
        ),
        migrations.AddField(
            model_name='local',
            name='rede',
            field=models.CharField(choices=[('1', '127/220 V'), ('2', '220/380 V')], default='1', max_length=1, verbose_name='Alimentação Concessionária'),
        ),
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilum', models.ManyToManyField(blank=True, related_name='demanda_ilum', to='instEletricas.cargasilum')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demanda_local', to='instEletricas.local')),
                ('tue', models.ManyToManyField(blank=True, related_name='demanda_tue', to='instEletricas.cargastue')),
                ('tug', models.ManyToManyField(blank=True, related_name='demanda_tug', to='instEletricas.cargastug')),
            ],
        ),
    ]
