# Generated by Django 5.2.5 on 2026-01-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0002_alter_local_bairro_alter_local_cidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='status',
            new_name='etapa',
        ),
    ]
