# Generated by Django 5.1.6 on 2025-11-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0003_circuitos_ckt_local_rede_demandas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ckt_local', to='instEletricas.local', verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='ilum',
            field=models.ManyToManyField(blank=True, related_name='ckt_ilum', to='instEletricas.cargasilum', verbose_name='Cargas de Iluminação'),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='tue',
            field=models.ManyToManyField(blank=True, related_name='ckt_tue', to='instEletricas.cargastue', verbose_name='Cargas TUEs'),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='tug',
            field=models.ManyToManyField(blank=True, related_name='ckt_tug', to='instEletricas.cargastug', verbose_name='Cargas TUGs'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='ilum',
            field=models.ManyToManyField(blank=True, related_name='demanda_ilum', to='instEletricas.cargasilum', verbose_name='Cargas de Iluminação'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='tue',
            field=models.ManyToManyField(blank=True, related_name='demanda_tue', to='instEletricas.cargastue', verbose_name='Cargas TUEs'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='tug',
            field=models.ManyToManyField(blank=True, related_name='demanda_tug', to='instEletricas.cargastug', verbose_name='Cargas TUGs'),
        ),
        migrations.CreateModel(
            name='Condutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ckts', models.IntegerField(default=1, verbose_name='Nº Máximo de CKTs em um trecho')),
                ('temp', models.IntegerField(default=30, verbose_name='Temperatura Ambiente Máxima')),
                ('mat_isol', models.CharField(choices=[('P', 'PVC'), ('E', 'EPR OU XLPE')], default='P', max_length=1, verbose_name='Material Isolante do Condutor')),
                ('ckt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cond_ckt', to='instEletricas.circuitos', verbose_name='Circuito')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cond_local', to='instEletricas.local', verbose_name='Local')),
            ],
        ),
    ]
