# Generated by Django 5.2.5 on 2026-01-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0003_rename_status_local_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='etapa',
            field=models.CharField(choices=[('1', 'Prospecção'), ('2', 'Captação de Documentos'), ('3', 'Captação de Dados'), ('4', 'Análise Técnica'), ('5', 'Orçamento'), ('6', 'Aprovação do Cliente'), ('7', 'Execução do Projeto'), ('8', 'Projeto Concluído')], default='1', max_length=1, verbose_name='Etapa do Projeto'),
        ),
    ]
