# Generated by Django 5.2.5 on 2025-11-13 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0004_alter_circuitos_ambiente_alter_circuitos_ilum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condutores',
            options={'verbose_name': 'Condutor', 'verbose_name_plural': 'Condutores'},
        ),
        migrations.AlterModelOptions(
            name='demandas',
            options={'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
        migrations.CreateModel(
            name='Protecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prot_ckt', to='instEletricas.condutores', verbose_name='Condutores')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prot_local', to='instEletricas.local', verbose_name='Local')),
            ],
        ),
    ]
