# Generated by Django 5.2.5 on 2026-01-12 03:10

import apps.cliente.validators
import apps.instEletricas.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0004_alter_local_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosInstEletricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Conta de Luz', 'Conta de Luz'), ('Diagrama Unifilar', 'Diagrama Unifilar'), ('Diagrama Trifilar', 'Diagrama Trifilar'), ('Planta do Imóvel', 'Planta do Imóvel'), ('ART do Projeto', 'ART do Projeto'), ('Memorial Descritivo', 'Memorial Descritivo'), ('Procuração', 'Procuração'), ('Documento do Cliente', 'Documento do Cliente'), ('Formulário de Solicitação', 'Formulário de Solicitação'), ('Proposta', 'Proposta'), ('Contrato Assinado', 'Contrato Assinado'), ('Orçamento', 'Orçamento'), ('Fotos', 'Fotos'), ('Outros', 'Outros')], default='Conta de Luz', max_length=100, verbose_name='Tipo de Arquivo')),
                ('arquivo', models.FileField(upload_to=apps.instEletricas.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'dwg']), apps.cliente.validators.validate_file_mimetype, apps.cliente.validators.validate_file_size], verbose_name='Arquivos')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_files', to='instEletricas.local')),
            ],
        ),
    ]
