# Generated by Django 5.2.5 on 2025-11-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0005_alter_condutores_options_alter_demandas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protecao',
            options={'verbose_name': 'Proteção', 'verbose_name_plural': 'Proteções'},
        ),
        migrations.CreateModel(
            name='Eletrodutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100, verbose_name='Trecho do Eletroduto')),
                ('conexoes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de Conexões para o eletroduto')),
                ('c_conex', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caracteristicas das conexões')),
                ('dist', models.IntegerField(blank=True, default=0, null=True, verbose_name='Comprimento do Trecho')),
                ('cond', models.ManyToManyField(blank=True, related_name='eletro_ckt', to='instEletricas.condutores', verbose_name='Condutores')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eletro_local', to='instEletricas.local', verbose_name='Local')),
            ],
        ),
    ]
