# Generated by Django 5.2.5 on 2025-11-14 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0006_alter_protecao_options_eletrodutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='nome',
            field=models.CharField(default='', max_length=50, verbose_name='Identificação do Circuito'),
        ),
        migrations.CreateModel(
            name='EquilibrioFases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckt', models.ManyToManyField(blank=True, related_name='EqFase_ckt', to='instEletricas.circuitos', verbose_name='Circuito')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EqFase_local', to='instEletricas.local', verbose_name='Local')),
            ],
        ),
    ]
