# Generated by Django 5.2.5 on 2025-11-15 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('instEletricas', '0007_alter_circuitos_nome_equilibriofases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_local', to='cliente.cliente', verbose_name='Cliente'),
        ),
    ]
