# Generated by Django 5.2.5 on 2025-11-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instEletricas', '0008_alter_local_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eletrodutos',
            options={'verbose_name': 'Eletroduto', 'verbose_name_plural': 'Eletrodutos'},
        ),
        migrations.AlterModelOptions(
            name='equilibriofases',
            options={'verbose_name': 'Equilíbrio de Fases', 'verbose_name_plural': 'Equilíbrio de Fases'},
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='iluminacao',
            field=models.IntegerField(default=0, verbose_name='Pontos de Iluminação Propostas'),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='tue',
            field=models.IntegerField(default=0, verbose_name='Qnt. TUEs Propostas'),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='tug',
            field=models.IntegerField(default=0, verbose_name='Qnt. TUGs Propostas'),
        ),
        migrations.AlterField(
            model_name='local',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='local',
            name='logradouro',
            field=models.CharField(max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.CharField(max_length=100, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='local',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
    ]
